<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>iml6yu.DataReceive.SerialCommunicate</Title>
    <Authors>iml6yu</Authors>
    <Description>串口数据采集类库</Description>
    <Copyright>@iml6yu</Copyright>
    <PackageIcon>logo_128.jpg</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageTags>serialcommunicate;datareceiver;iml6yu;iml6yu.data;</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\..\..\logo_128.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
    <PackageReference Include="System.IO.Ports" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="System.IO.Ports" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\iml6yu.DataReceive.Core\iml6yu.DataReceive.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>