<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-iml6yu.DataReceiverExample-96157aa8-49b2-41ce-9512-3c275aee7e34</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="iml6yu.DataReceive.PLCSiemens" Version="1.2.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>
</Project>
